networks:
  monitoring: {}

volumes:
  prometheus_storage: {}
  grafana_storage: {}

services:
  mktxp:
    container_name: mktxp
    image: ghcr.io/akpw/mktxp:latest
    user: root
    volumes:
      - './mktxp/:/root/mktxp/'
    networks:
      monitoring: null
    restart: unless-stopped  

  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_DEFAULT_THEME: "dark"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/mikrotik/mikrotik_mktxp_exporter.json
    image: grafana/grafana:latest
    networks:
      monitoring: null
    ports:
    - protocol: tcp
      published: 3003
      target: 3000
    restart: unless-stopped
    volumes:
    -  grafana_storage:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro

  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:latest
    networks:
      monitoring: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: unless-stopped
    volumes:
    - ./loki/loki-config.yml:/etc/loki/loki-config.yml

  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=1y
    - --web.enable-admin-api
    - --web.enable-lifecycle
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      monitoring: null
    ports:
    - published: 9090
      target: 9090
    restart: unless-stopped
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_storage:/prometheus

  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:latest
    networks:
      monitoring: null
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: unless-stopped
    volumes:
    - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro

  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      monitoring: null
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: unless-stopped
    volumes:
    - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
  
  blackbox:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox-exporter
    command: --config.file=/config/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/config/blackbox.yml
    networks:
      monitoring: null
    ports:
      - protocol: tcp
        published: 9115
        target: 9115
    restart: unless-stopped
